ITEMS = {
    { "key_of_hope", "toggle" },
    { "key_of_chaos", "toggle" },
    { "key_of_courage", "toggle" },
    { "key_of_love", "toggle" },
    { "key_of_strength", "toggle" },
    { "key_of_symbiosis", "toggle" },
    { "windmill", "toggle" },
    { "wingsuit", "toggle" },
    { "grapplou", "toggle" },
    { "lightfoot_tabi", "toggle" },
    { "candle", "toggle" },
    { "seashell", "toggle" },
    { "power_thistle", "toggle" },
    { "demon_king_crown", "toggle" },
    { "ruxxtin_amulet", "toggle" },
    { "fairy_bottle", "toggle" },
    { "sun_crest", "toggle" },
    { "moon_crest", "toggle" },
    { "necro", "toggle" },
    { "pyro", "toggle" },
    { "claustro", "toggle" },
    { "acro", "toggle" },
    { "power_seal", "consumable" },
    { "time_shard", "consumable" },
    { "time_shard_10" },
    { "time_shard_50" },
    { "time_shard_100" },
    { "time_shard_300" },
    { "time_shard_500" },
    { "karuta_plates", "toggle" },
    { "serendipitous_bodies", "toggle" },
    { "path_of_resilience", "toggle" },
    { "kusari_jacket", "toggle" },
    { "energy_shuriken", "toggle" },
    { "serendipitous_minds", "toggle" },
    { "prepared_mind", "toggle" },
    { "meditation", "toggle" },
    { "rejuvenative_spirit", "toggle" },
    { "centered_mind", "toggle" },
    { "strike_of_the_ninja", "toggle" },
    { "second_wind", "toggle" },
    { "currents_master", "toggle" },
    { "aerobatics_warrior", "toggle" },
    { "demons_bane", "toggle" },
    { "devils_due", "toggle" },
    { "time_sense", "toggle" },
    { "power_sense", "toggle" },
    { "focused_power_sense", "toggle" },
    { "green_kappa", "toggle" },
    { "blue_kappa", "toggle" },
    { "ountarde", "toggle" },
    { "red_kappa", "toggle" },
    { "demon_king", "toggle" },
    { "quillshroom", "toggle" },
    { "jumping_quillshroom", "toggle" },
    { "scurubu", "toggle" },
    { "jumping_scurubu", "toggle" },
    { "wallaxer", "toggle" },
    { "barmathazel", "toggle" },
    { "queen_of_quills", "toggle" },
    { "demon_hive", "toggle" },
    { "money_wrench", "toggle" },
}

ITEM_MAPPING = {}
for n, item in ipairs(ITEMS) do
    ITEM_MAPPING[0xADD000 + n - 1] = item
end
