SHOP_DATA = {
    { "HP_UPGRADE_1", "Karuta Plates" },
    { "ENEMY_DROP_HP", "Serendipitous Bodies" },
    { "DAMAGE_REDUCTION", "Path of Resilience" },
    { "HP_UPGRADE_2", "Kusari Jacket" },
    { "SHURIKEN", "Energy Shuriken" },
    { "ENEMY_DROP_MANA", "Serendipitous Minds" },
    { "SHURIKEN_UPGRADE_1", "Prepared Mind" },
    { "CHECKPOINT_FULL", "Meditation" },
    { "POTION_FULL_HEAL_AND_HP", "Rejuvenative Spirit" },
    { "SHURIKEN_UPGRADE_2", "Centered Mind" },
    { "ATTACK_PROJECTILE", "Strike of the Ninja" },
    { "AIR_RECOVER", "Second Wind" },
    { "SWIM_DASH", "Currents Master" },
    { "GLIDE_ATTACK", "Aerobatics Warrior" },
    { "CHARGED_ATTACK", "Demon's Bane" },
    { "QUARBLE_DISCOUNT_50", "Devil's Due" },
    { "TIME_WARP", "Time Sense" },
    { "POWER_SEAL", "Power Sense" },
    { "POWER_SEAL_WORLD_MAP", "Focused Power Sense" },
}

FIGURINE_DATA = {
    { "GREEN_KAPPA", "Green Kappa Figurine" },
    { "BLUE_KAPPA", "Blue Kappa Figurine" },
    { "OUNTARDE", "Ountarde Figurine" },
    { "RED_KAPPA", "Red Kappa Figurine" },
    { "DEMON_KING", "Demon King Figurine" },
    { "QUILLSHROOM", "Quillshroom Figurine" },
    { "JUMPING_QUILLSHROOM", "Jumping Quillshroom Figurine" },
    { "SCURUBU", "Scurubu Figurine" },
    { "JUMPING_SCURUBU", "Jumping Scurubu Figurine" },
    { "WALLAXER", "Wallaxer Figurine" },
    { "BARMATHAZEL", "Barmath'azel Figurine" },
    { "QUEEN_OF_QUILLS", "Queen of Quills Figurine" },
    { "DEMON_HIVE", "Demon Hive Figurine" },
}

PREREQS = {
    ["Serendipitous Bodies"] = "Karuta Plates",
    ["Path of Resilience"] = "Serendipitous Bodies",
    ["Kusari Jacket"] = "Path of Resilience",
    ["Serendipitous Minds"] = "Energy Shuriken",
    ["Prepared Mind"] = "Serendipitous Minds",
    ["Meditation"] = { "Prepared Mind", "Kusari Jacket" },
    ["Rejuvenative Spirit"] = "Meditation",
    ["Centered Mind"] = "Meditation",
    ["Second Wind"] = "Strike of the Ninja",
    ["Currents Master"] = "Second Wind",
    ["Aerobatics Warrior"] = "Currents Master",
    ["Demon's Bane"] = { "Rejuvenative Spirit", "Aerobatics Warrior" },
    ["Power Sense"] = "Time Sense",
    ["Focused Power Sense"] = "Power Sense",
}
print("shop data loaded!")